Repository jenkins-infra/uplink, pull requests merged in 2025-05, with the labels that each got.

#58 feat!: bump NodeJS from 9 to 20 (LTS)
  Dockerfile
  tools/node
Labels: enhancement, breaking

#61 feat!: Bump NodeJS to 22 , `pg` lib to `8.16` and sequelize lib to `5.22`
  Dockerfile
  config/database.js
  docker-compose.yml
  docker/pg_hba.conf
  package-lock.json
  package.json
  src/models/index.ts
  src/services/events.ts
  test/app.test.ts
  test/events.test.ts
  test/types.test.ts
Labels: enhancement, breaking

#63 chore(Jenkinsfile) enable Docker image CD on infra.ci (automatic semantic release)
  Jenkinsfile
Labels: chore

#64 fix(dockerfile) use an entrypoint script as default CMD to ensure application is always executed after db-migrate task
  Dockerfile
  entrypoint.sh
Labels: bug, docker
